# Generated by Django 3.0.8 on 2020-07-17 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=20)),
                ('productPrice', models.CharField(max_length=7)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=7)),
                ('paymentMethod', models.CharField(max_length=50)),
                ('dateOfPurchase', models.CharField(max_length=80)),
                ('productName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Item')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Login')),
            ],
        ),
    ]
